// Per-page OG cards for the solutions routes, generated by
// scripts/og-image/generate-og.mjs from scripts/og-image/solutions.json into
// public/og/solutions/. The manifest is the list of cards that exist; a slug
// with no entry (a CMS-only page, or a card that was never generated) falls
// back to the site-wide default image.

import manifest from "@/scripts/og-image/solutions.json";

/** One manifest entry (see scripts/og-image/README.md). */
interface OgManifestEntry {
  title?: string;
  out?: string;
  slug?: string;
}

/** Prefix the generator's output paths carry; stripped to get the URL path. */
const PUBLIC_PREFIX = "public";

/** Slug to public URL path, built once from the manifest. */
const OG_IMAGE_BY_SLUG: Readonly<Record<string, string>> = (() => {
  try {
    const entries = (Array.isArray(manifest) ? manifest : []) as OgManifestEntry[];
    const map: Record<string, string> = {};
    for (const entry of entries) {
      if (!entry?.slug || !entry?.out) {
        continue;
      }
      const out = entry.out.replace(/\\/g, "/");
      map[entry.slug] = out.startsWith(`${PUBLIC_PREFIX}/`)
        ? out.slice(PUBLIC_PREFIX.length)
        : `/${out.replace(/^\/+/, "")}`;
    }
    return map;
  } catch {
    return {};
  }
})();

/**
 * The generated OG card for a solutions slug (or "index" for /solutions).
 *
 * @param slug - The page slug.
 * @returns The public path, or undefined when no card was generated.
 */
export function getSolutionOgImage(slug: string): string | undefined {
  try {
    return OG_IMAGE_BY_SLUG[slug];
  } catch {
    return undefined;
  }
}
